name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: rustfmt
            override: true
      - uses: mbrobbel/rustfmt-check@0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2
      - name: Checkout SKE repo
        uses: actions/checkout@v2
        with:
          repository: aeronautical-informatics/ske
          ref: refs/tags/v2.0.0
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          path: ske
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-clippy-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            override: true
      - name: Deploy libskeserver.so
        run: cp ${{ github.workspace }}/ske/bin/libskeserver.so ./
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2
      - name: Checkout SKE repo
        uses: actions/checkout@v2
        with:
          repository: aeronautical-informatics/ske
          ref: refs/tags/v2.0.0
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          path: ske
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable 
          target: x86_64-unknown-linux-gnu
          override: true
      - name: Deploy libskeserver.so
        run: cp ${{ github.workspace }}/ske/bin/libskeserver.so ./
      - name: Build ske-rs
        run: cargo build --release --verbose
      - uses: actions/upload-artifact@v2
        with:
          name: ske-rs
          path: target/release/ske-rs
